//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public long PaymentDetailsId { get; set; }
        public string PaymentType { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> TdsAmount { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public string InvoiceNo { get; set; }
        public string ChequeNo { get; set; }
        public string TransactionId { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<long> FirmId { get; set; }
        public string PfCode { get; set; }
        public string CompanyName { get; set; }
        public Nullable<double> Paid { get; set; }
    }
}
